# Where should we write the GIF?
Output ../gifs/banner.gif

# Set up a 1200x600 terminal with 46px font.
Set Shell zsh
Set FontSize 40
Set Width 2150
Set Height 1200
Set PlaybackSpeed 1.0
Set TypingSpeed 50ms
Set Framerate 24

Type "./load-github-banner.sh"
Enter

Sleep 20

Type "./list-skills.sh"
Sleep 4
Enter
Sleep 3
Space
Down
Sleep 3
Space
Down
Sleep 3
Space
Down
Sleep 3
Space
Sleep 3
Enter

Sleep 20

Type "clear"
Sleep 3
Enter
